### PR TITLE
Added -Wno-ignored-attribute for clang/gcc.

### PR DESCRIPTION
**Pull request by cmumford**
Compiler warning when unable to inline a template./

### CODE REVIEW

**Comment by pwnall** [comment]
How about deciding that we'll support `-Wall -Werror` on clang, but only do best-effort support on GCC?

I'd like us to support `-Wall -Werror` in clang w/o exceptions so we can make it easy to integrate Snappy into other Google products, like Chrome. Also, if needed, I think we could tweak the internal config to make sure that `-Wall` works.

**Comment by cmumford** [comment]
I'm fine with that approach. There seem to be several clang's in [CMAKE_CXX_COMPILER_ID](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html), but only one that appears to be GCC ("GNU"), so I can test against that. I'll put together a second PR with that change.

**Comment by cmumford** [comment]
Replacement PR is https://github.com/google/snappy/pull/113

**Comment by cmumford** [comment]
Oops - 113 was bad. Instead going with https://github.com/google/snappy/pull/114

**Pull request closed without merging**
