### PR TITLE
gtest should be found while build with testing

### PR DESCRIPTION
**Pull request by ClausKlein**
add debug suffix to enable debug and release installation

### CODE REVIEW

**Comment by ClausKlein** [comment]
bash-4.4$ sudo ninja install
Password:
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libsnappy.a
-- Up-to-date: /usr/local/include/snappy-c.h
-- Up-to-date: /usr/local/include/snappy-sinksource.h
-- Up-to-date: /usr/local/include/snappy.h
-- Installing: /usr/local/include/snappy-stubs-public.h
-- Installing: /usr/local/lib/cmake/Snappy/SnappyTargets.cmake
-- Installing: /usr/local/lib/cmake/Snappy/SnappyTargets-release.cmake
-- Up-to-date: /usr/local/lib/cmake/Snappy/SnappyConfig.cmake
-- Installing: /usr/local/lib/cmake/Snappy/SnappyConfigVersion.cmake
bash-4.4$ ninja clean
[1/1] Cleaning all built files...
Cleaning... 8 files.
bash-4.4$ ninja
[8/8] Linking CXX executable snappy_unittest
bash-4.4$ ctest
Test project /Users/clausklein/Workspace/cpp/snappy/build
    Start 1: snappy_unittest
1/1 Test #1: snappy_unittest ..................***Exception: Child aborted 43.15 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  43.19 sec

The following tests FAILED:
	  1 - snappy_unittest (Child aborted)
Errors while running CTest
bash-4.4$

**Comment by ClausKlein** [comment]
a debug build works?

bash-4.4$ ctest
Test project /Users/clausklein/Workspace/cpp/snappy/build
    Start 1: snappy_unittest
1/1 Test #1: snappy_unittest ..................   Passed   91.10 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  91.12 sec
bash-4.4$

**Comment by ClausKlein** [comment]
no idea if someone is interested in this info, but your unit tests are fakes, as long gtest is not installed!
==========================================================================

see *.yam

**Comment by pwnall** [comment]
Google Test can be used, but is not necessary to run Snappy's tests. See `snappy-test.h` and `snappy-test.cc`

**Comment by ClausKlein** [comment]
and what is about the failed release build test:
1/1 Test #1: snappy_unittest ..................***Exception: Child aborted 43.15 sec

**Comment by ClausKlein** [comment]
bash-4.4$ build/snappy_unittest 
Running microbenchmarks.
Benchmark            Time(ns)    CPU(ns) Iterations
---------------------------------------------------
BM_UFlat/0             124472     111182       1383 878.3MB/s  html
BM_UFlat/1            1116685    1104740        162 606.1MB/s  urls
BM_UFlat/2              17499      15549      13114 7.4GB/s  jpg
BM_UFlat/3                347        342     465116 557.0MB/s  jpg_200
BM_UFlat/4              23153      21893       8756 4.4GB/s  pdf
BM_UFlat/5             457441     452747        356 862.8MB/s  html4
BM_UFlat/6             374863     371730        441 390.2MB/s  txt1
BM_UFlat/7             332021     328297        511 363.6MB/s  txt2
BM_UFlat/8             991675     983406        182 413.9MB/s  txt3
BM_UFlat/9            1381432    1353679        134 339.5MB/s  txt4
BM_UFlat/10            108142     106358       1903 1.0GB/s  pb
BM_UFlat/11            389176     377503        431 465.6MB/s  gaviota
BM_UIOVec/0            282930     279938        715 348.8MB/s  html
BM_UIOVec/1           2508710    2482530        100 269.7MB/s  urls
BM_UIOVec/2             17226      16062      10400 7.1GB/s  jpg
BM_UIOVec/3               844        837      84033 227.7MB/s  jpg_200
BM_UIOVec/4             37455      37061       5411 2.6GB/s  pdf
BM_UValidate/0          42784      42388       3930 2.2GB/s  html
BM_UValidate/1         500854     487199        351 1.3GB/s  urls
BM_UValidate/2            233        231     500000 495.9GB/s  jpg
BM_UValidate/3            160        158    1111111 1.2GB/s  jpg_200
BM_UValidate/4           4025       3980      49875 24.0GB/s  pdf
BM_ZFlat/0             215939     212595        946 459.4MB/s  html (22.31 %)
BM_ZFlat/1            2785130    2757490        100 242.8MB/s  urls (47.78 %)
BM_ZFlat/2              20388      20168       9842 5.7GB/s  jpg (99.95 %)
BM_ZFlat/3                896        888     215053 214.8MB/s  jpg_200 (73.00 %)
BM_ZFlat/4              35369      35037       4498 2.7GB/s  pdf (83.30 %)
BM_ZFlat/5             857840     850415        200 459.3MB/s  html4 (22.52 %)
BM_ZFlat/6             781459     773459        224 187.5MB/s  txt1 (57.88 %)
BM_ZFlat/7             695886     687674        255 173.6MB/s  txt2 (61.91 %)
BM_ZFlat/8            2109630    2086450        100 195.1MB/s  txt3 (54.99 %)
BM_ZFlat/9            2835270    2804940        100 163.8MB/s  txt4 (66.26 %)
BM_ZFlat/10            216904     205074        894 551.5MB/s  pb (19.68 %)
BM_ZFlat/11            652560     565756        325 310.7MB/s  gaviota (37.72 %)

Running correctness tests.
Crazy decompression lengths not checked on 64-bit build

Abort trap: 6
bash-4.4$ 

„Es ist nicht genug, zu wissen, man muß auch anwenden; 
     es ist nicht genug, zu wollen, man muß auch tun.“ 
Johann Wolfgang von Goethe <http://www.zitate-online.de/autor/goethe-johann-wolfgang-von/> (Werk: Wilhelm Meisters Wanderjahre)

**Comment by ClausKlein** [comment]
[ RUN      ] Snappy.FindMatchLength
../snappy_unittest.cc:954: Failure
      Expected: 6
To be equal to: TestFindMatchLength("012345", "012345", 6)
      Which is: 8
[  FAILED  ] Snappy.FindMatchLength (1 ms)

**Pull request closed without merging**
