### PR TITLE
fix cmake build error

### PR DESCRIPTION
**Pull request by LYKZZzz**
I want to install libsnappy on linux mint 19. I already install GTest from github, but make complained undefined reference:
```
[100%] Linking CXX executable snappy_unittest
CMakeFiles/snappy_unittest.dir/snappy_unittest.cc.o: In function `snappy::Snappy_ZeroOffsetCopy_Test::TestBody()':
snappy_unittest.cc:(.text+0x680b): undefined reference to `testing::Message::Message()'
```

It seems like CMakeList not link0 to libgtest.  Fix it by adding ```target_link_libraries(snappy_unittest gtest)``` in CMakelists.txt

### CODE REVIEW

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by pwnall** [comment]
If you're installing snappy for use with other projects, you should use the following CMake flags:

```bash
cmake  -DSNAPPY_BUILD_TESTS=0 -DCMAKE_BUILD_TYPE=Release ..
```

@cmumford WDYT about updating our README files across snappy, leveldb and crc32c? I'm now mildly concerned that folks are following our instructions to the letter, and burning power running un-optimized versions of our libraries.

**Comment by cmumford** [comment]
@pwnall I'm OK with changing the README's

**Comment by xkszltl** [comment]
May I ask why the unit test should be disabled?
In my use case I build the latest snappy and pack it into deb/rpm for use, in both docker and host environment.
I'd like to have a way to quickly verify the lib is working by its own, before installing and providing it to downstream dependencies

**Comment by ShraddhaDevaiya** [comment]
I was finding about the link0 command in Linux but  I didn't get much and I found this conversation.
So can you please help to know about what is link0 actually, If possible ? because I need to use it somewhere else.

**Comment by pwnall** [comment]
Thank you for your contribution!

We're not currently interested in contributions to the build configuration. We now have a paragraph explaining the situation in https://github.com/google/snappy/blob/master/README.md#contributing-to-the-snappy-project

**Pull request closed without merging**
