### PR TITLE
Readd pkgconfig support.

### PR DESCRIPTION
**Pull request by niclasr**
Readd pkgconfig support to support usage of snappy with other buildsystems.

### CODE REVIEW

**Comment by niclasr** [comment]
I signed it!

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by ffontaine** [comment]
`snappy.pc.in` should be updated with the following line so applications statically linking with snappy (such as wireshark) could retrieve this dependency: 
`Libs.private: -lstdc++`

**Comment by niclasr** [comment]
Well @ffontaine libstdc++ is the c++ runtime used by gcc, if another compiler like clang is used libc++ is used instead so then it must be -lc++. so hardcoding it is not a good idea. wireshark does not use pkgconfig to find snappy from what I have seen, it uses find_package(Snappy). wireshark obviously does not use the c++ compiler when linking to snappy and thereby missing the c++ runtime. Snappy can make the software that depend on it via find_package to use c++ for linking with the static library by setting the property IMPORTED_LINK_INTERFACE_LANGUAGES to CXX on the snappy target and using the keyword EXPORT_LINK_INTERFACE_LIBRARIES in the install(EXPORTS ...) command. I think that would be something to add.

**Comment by pwnall** [comment]
We will not add pkg-config support for now.

We don't want to get into supporting individual package managers, because the C++ ecosystem hasn't converged into a single solution, and there are quite a few equally reasonable candidates. We can't justify the investment into supporting all the package managers, or into supporting a couple of package managers and trying to rationalize where we drew the line.

**Pull request closed without merging**
