### PR TITLE
travis multiarch tests

### PR DESCRIPTION
**Pull request by grooverdan**
started thanks to @pwnall in #91

### CODE REVIEW

**Comment by grooverdan** [comment]
s390x failure, https://travis-ci.community/t/s90x-adding-apt-sources-no-usable-temporary-directory-found/8635, so moving to allowed failures.

**Comment by abebeos** [comment]
@grooverdan , what is the status of this (and of the snappy project, as it seems simply to be a public repo, not a public OSS-project with usual contribution processes)? Can I assist you with something to get this merged?

@pwnall is "currently focused on the needs of Google Chrome", is there any standard-process @ google to get some other project-manager active?

**Comment by grooverdan** [comment]
@abebeos  I cannot provide more information than what is originally here. If you have signed a CLA you could push a commit that resolves the .travis.yml conflict. If you push to https://github.com/grooverdan/snappy/tree/travis-arch I'll merge it and it should end up here. I don't know if that will help, but its one less barrier. My CLA is tied to IBM and I'm not employed there any more so me fixing this adds to the legal complication. I'm not going through the CLA process for a dormant PR at this stage.

**Comment by abebeos** [comment]
@grooverdan , thank you for your quick response. It sounds like its better to send a new PR in, I've a CLA on file anyways.

I'll start from scratch, trying to change as less as possible, in order to make review easier (my personal experience tells me that even slight changes in logic/structure/flow can lead to review-delays).

Just one thing: how confident are you about your introduced changes/additions (do I need to verify much, or have you verified those e.g. in other ci setups)?

**Comment by grooverdan** [comment]
sure. closing this to avoid confusion. good luck.

**Pull request closed without merging**
