### PR TITLE
Add .gitignore to ignore build artifacts

### PR DESCRIPTION
**Pull request by tmm1**
Makes `git status` clean on a fresh clone + build.

### CODE REVIEW

**Comment by pwnall** [comment]
Agreed that having a `.gitignore` would be a good idea.

That being said... what version of snappy are you using? `master` uses CMake, and all build artifacts should be isolated to a single directory. The README recommends `build/` as the build directory name, so I think that's all

**Comment by tmm1** [comment]
Looks like I'm on 32d6d7d8a2ef328a2ee1dd40f072e21f4983ebda which was a bit before v1.1.4

**Comment by tmm1** [comment]
Can we atleast add `/build` to `.gitignore` then?

**Comment by pwnall** [comment]
That sounds good. Would you like to update your PR, or should we pursue that separately?

**Comment by tmm1** [comment]
I will close this PR. I can create a new PR but I think it would be simpler for you to just create a .gitignore with the single entry.

**Pull request closed without merging**
