### PR TITLE
Revert "Add absl::GetFlag and absl::SetFlag to uses of flags."

### PR DESCRIPTION
**Pull request by abebeos**
revert ci-breaking 453942b

@cmumford, last commit breaks the build.

### CODE REVIEW

**Comment by pwnall** [comment]
Thank you for your contribution!

Snappy is mainly developed by Google and published as open source on GitHub. Unfortunately, the development workflow is not intuitive for external developers accustomed to GitHub. TBH, we're still iterating on the best way to integrate GitHub contributions in our workflow.

In this particular case -- we cannot revert the CL referenced above, as it would have negative internal consequences. We'll have to work on fixing the errors introduced instead. This work can only be done by a Googler, because a good fix needs to also work for the internal repository.

I'm sorry for the disappointing answer. I hope the text above makes it clear that we're not closing this PR lightly.

**Comment by abebeos** [comment]
)_@_$*_%@)(*#$_)(*@#$%

**Comment by abebeos** [comment]
[...]
> I'm sorry for the disappointing answer. I hope the text above makes it clear that we're not closing this PR lightly.

What is disappoint is that Google obviously does not follow the very basic rule:

"If master breaks, do not merge"

Anyways, ty for your quick response.

**Comment by abebeos** [comment]
https://chromium.googlesource.com/external/github.com/google/snappy/+/453942b38fa3317c7580f1d8478bdcfd83ea6149

**Comment by djbtav** [comment]
https://m.kitpor.com/ar/buy

**Comment by djbtav** [comment]
https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-3227144438472147&output=html&h=300&w=414&bih=720&biw=414&adx=0&ady=623&ga_hid=5717&slotname=2151093491&adk=321429318&url=https://www.dz-techs.com/hack-snapchat-and-protect/&eid=368226511&u_his=3&brdim=0,0,0,0,414,0,414,896,414,720&is_amp=5&prev_fmts=414x300_0ads_al&format=fpkc_al_lp&kw_type=radlink&hl=ar&rt=ChBgPYazAArn5QqFgRo5Dj1PEgEgGgigyutLVJf6YygBUhMInvGIha2Q7wIV0MneCh2Q7QuFeAGCASgKJNio2LHZhtin2YXYrCDYqtmH2YPZitixINit2LPYp9io2KfYqhIAggElCiHYs9ix2YLYqSDYrdiz2KfYqCDYs9mG2KfYqCDYtNin2KoSAIIBFwoT2KjYsdmG2KfZhdisINmH2YPYsRIAggEeChpIYWNrIHNuYXBjaGF0INio2LHZhtin2YXYrBIAggEbChfYqNix2KfZhdisINin2K7Yqtix2KfZghIAggEXChPYqtmH2YPZitixIHNuYXBjaGF0EgCIAQQ&ad_type=text

**Comment by abebeos** [comment]
related: https://github.com/abseil/abseil-cpp/issues/911#issuecomment-791418461

**Pull request closed without merging**
